title: Physics Alumni Society MCC
logo: /assets/img/logo.png
description: Alumni Group for Physics Alumni of Madras Christian College
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
