title: Physics Alumni Society MCC
logo: /assets/img/logo.png
description: Official website of the Physics Alumni Society, Malabar Christian College (MCC), Calicut. Connecting physics alumni, showcasing achievements, and documenting endowment lectures and alumni meets.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
